# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dbe92d75b95bbae5496ef1794a6cb752"
name = "buyense-search-trung"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_app_proxy"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
