# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "922fd6e00a765659ee8b56ac583cf542"
name = "AI-Buyense"
application_url = "https://buysenseshopify.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-10"

[[webhooks.subscriptions]]
topics = [ "app_subscriptions/update" ]
uri = "/webhooks/app/subscriptions_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,read_locales,write_app_proxy"

[auth]
redirect_urls = [ "https://buysenseshopify.com/auth/callback" ]

[app_proxy]
url = "/proxy/ai-search"
subpath = "ai-search"
prefix = "apps"

[[access.metafields]]
namespace = "ai_search"
key = "theme_map"
access = "public_read"
