# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "922fd6e00a765659ee8b56ac583cf542"
name = "AI-Buyense"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_app_proxy"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "/proxy/ai-search"
subpath = "ai-search"
prefix = "apps"
