# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e6b610e31c77e8bc9274b137dbee44c5"
application_url = "https://example.com"
embedded = true
name = "AI-Buyense"


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_app_proxy"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2026-10"

[app_proxy]
url = "/proxy/ai-search"
prefix = "apps"
subpath = "ai-search"

[build]
automatically_update_urls_on_dev = true

[[access.metafields]]
namespace = "ai_search"
key = "theme_map"
access = "public_read"
