CREATE TABLE `AiSearchAttempt` (
  `id` VARCHAR(64) NOT NULL,
  `shop` VARCHAR(191) NOT NULL,
  `purpose` VARCHAR(64) NOT NULL,
  `queryHash` VARCHAR(64) NOT NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'STARTED',
  `failureKind` VARCHAR(64) NULL,
  `reason` VARCHAR(191) NULL,
  `aiExecuted` BOOLEAN NOT NULL DEFAULT false,
  `cacheHit` BOOLEAN NOT NULL DEFAULT false,
  `nativeFallback` BOOLEAN NOT NULL DEFAULT false,
  `resultCount` INTEGER NULL,
  `searchLogId` VARCHAR(191) NULL,
  `reservationId` VARCHAR(191) NULL,
  `periodId` INTEGER NULL,
  `durationMs` INTEGER NULL,
  `httpStatus` INTEGER NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `finishedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `AiSearchAttempt_searchLogId_key` (`searchLogId`),
  INDEX `AiSearchAttempt_shop_createdAt_idx` (`shop`, `createdAt`),
  INDEX `AiSearchAttempt_shop_status_createdAt_idx` (`shop`, `status`, `createdAt`),
  INDEX `AiSearchAttempt_createdAt_idx` (`createdAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
