import assert from "node:assert/strict";
import {buildQuerySemanticProfile,isGenericDiscoveryFamily} from "../app/services/search/query-semantic-profile.server";
const query="dress for snowboarding";
const raw:any={rawQuery:query,normalizedQuery:query,foldedQuery:query,route:"FULL_LLM",retrievalMode:"DIRECT",referenceTerms:[],identities:[{value:"dress",normalizedValue:"dress",mode:"MUST",confidence:1,source:"DICTIONARY"}],entities:{brands:[],models:[],identifiers:[]},attributes:[],measurements:[],audiences:[],contexts:[],compatibility:[],relation:"SINGLE",marketPreference:"ANY",sort:{field:"RELEVANCE"},semanticQuery:query,resolvedSegments:[],unresolvedSegments:[],routerReason:[],versions:{dictionaryVersion:"fixture",queryParserVersion:"fixture",queryRouterVersion:"fixture"}};
const llm:any={query:"looking for winter clothing",rewritten:true,catalogRelevant:true,analysis:{intent:"looking for winter clothing",detectedLanguage:"en",shopLanguage:"en",confidence:1,productType:"winter clothing",productTypes:["winter clothing"],productRelation:"SINGLE",shopLanguageProductType:"winter clothing",category:"",brands:[],models:[],identifiers:[],audience:[],requiredAttributes:[],optionalPreferences:[],attributes:[],useCases:[],compatibility:[],entities:[],shopLanguageTerms:[],englishTerms:[],negativeAttributes:[],negativeTerms:[],semanticMustTerms:[],semanticSourceMustTerms:[],semanticMustNotTerms:[],semanticExpansions:[],matchedCatalogTerms:[],decisionReason:"fixture",sortIntent:"RELEVANCE",marketPreference:"ANY",semanticMandatoryConcepts:[{source:"snowboarding",target:"winter activity"}],semanticDemand:{identity:["winter clothing"],desiredOutcomes:[],useCases:["snowboarding"],contexts:[],qualities:[],audience:[],styles:[],negativeConstraints:[],exactConstraints:[]}}};
const profile=buildQuerySemanticProfile({originalQuery:query,rawPlan:raw,expandedPlan:raw,llm});
assert.deepEqual(profile.rewrite.analysis.sourceOwnedTargetIdentities,["dress"],"LLM omission cannot revoke source-owned parser target");
assert.ok(profile.embeddingInput.toLowerCase().includes("dress"),"primary Demand must retain authoritative source target");
assert.ok(!profile.rewrite.analysis.semanticDemand?.identity.includes("winter clothing"),"unsupported inferred class must not replace source target");
for(const broad of ["clothes","clothing","winter apparel","casual outfits","travel gear"]){assert.ok(isGenericDiscoveryFamily(broad),`${broad}: broad family stays discovery`);}
console.log("PASS: deterministic target survives incomplete LLM; generic family morphology stays discovery");
